
package edu.cibertec.jaad.ws.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicAlumnoServiceService", targetNamespace = "http://jaxws.ws.jaad.cibertec.edu/", wsdlLocation = "file:/C:/JAAD-2016-1/03_Laboratorios/Modulo01/LABM1C3-06WSAuth-client/src/wsdl/alumno.wsdl")
public class BasicAlumnoServiceService
    extends Service
{

    private final static URL BASICALUMNOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICALUMNOSERVICESERVICE_EXCEPTION;
    private final static QName BASICALUMNOSERVICESERVICE_QNAME = new QName("http://jaxws.ws.jaad.cibertec.edu/", "BasicAlumnoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/JAAD-2016-1/03_Laboratorios/Modulo01/LABM1C3-06WSAuth-client/src/wsdl/alumno.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICALUMNOSERVICESERVICE_WSDL_LOCATION = url;
        BASICALUMNOSERVICESERVICE_EXCEPTION = e;
    }

    public BasicAlumnoServiceService() {
        super(__getWsdlLocation(), BASICALUMNOSERVICESERVICE_QNAME);
    }

    public BasicAlumnoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICALUMNOSERVICESERVICE_QNAME, features);
    }

    public BasicAlumnoServiceService(URL wsdlLocation) {
        super(wsdlLocation, BASICALUMNOSERVICESERVICE_QNAME);
    }

    public BasicAlumnoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICALUMNOSERVICESERVICE_QNAME, features);
    }

    public BasicAlumnoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicAlumnoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlumnoService
     */
    @WebEndpoint(name = "BasicAlumnoServicePort")
    public AlumnoService getBasicAlumnoServicePort() {
        return super.getPort(new QName("http://jaxws.ws.jaad.cibertec.edu/", "BasicAlumnoServicePort"), AlumnoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlumnoService
     */
    @WebEndpoint(name = "BasicAlumnoServicePort")
    public AlumnoService getBasicAlumnoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.ws.jaad.cibertec.edu/", "BasicAlumnoServicePort"), AlumnoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICALUMNOSERVICESERVICE_EXCEPTION!= null) {
            throw BASICALUMNOSERVICESERVICE_EXCEPTION;
        }
        return BASICALUMNOSERVICESERVICE_WSDL_LOCATION;
    }

}
