
package edu.cibertec.jaad.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicCalculadoraService", targetNamespace = "http://jaxws.jaad.cibertec.edu/", wsdlLocation = "file:/C:/JAAD-2016-1/03_Laboratorios/Modulo01/LABM1C3-04WSMvn/src/wsdl/calcws.wsdl")
public class BasicCalculadoraService
    extends Service
{

    private final static URL BASICCALCULADORASERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICCALCULADORASERVICE_EXCEPTION;
    private final static QName BASICCALCULADORASERVICE_QNAME = new QName("http://jaxws.jaad.cibertec.edu/", "BasicCalculadoraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/JAAD-2016-1/03_Laboratorios/Modulo01/LABM1C3-04WSMvn/src/wsdl/calcws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICCALCULADORASERVICE_WSDL_LOCATION = url;
        BASICCALCULADORASERVICE_EXCEPTION = e;
    }

    public BasicCalculadoraService() {
        super(__getWsdlLocation(), BASICCALCULADORASERVICE_QNAME);
    }

    public BasicCalculadoraService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICCALCULADORASERVICE_QNAME, features);
    }

    public BasicCalculadoraService(URL wsdlLocation) {
        super(wsdlLocation, BASICCALCULADORASERVICE_QNAME);
    }

    public BasicCalculadoraService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICCALCULADORASERVICE_QNAME, features);
    }

    public BasicCalculadoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicCalculadoraService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "BasicCalculadoraPort")
    public Calculadora getBasicCalculadoraPort() {
        return super.getPort(new QName("http://jaxws.jaad.cibertec.edu/", "BasicCalculadoraPort"), Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "BasicCalculadoraPort")
    public Calculadora getBasicCalculadoraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.jaad.cibertec.edu/", "BasicCalculadoraPort"), Calculadora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICCALCULADORASERVICE_EXCEPTION!= null) {
            throw BASICCALCULADORASERVICE_EXCEPTION;
        }
        return BASICCALCULADORASERVICE_WSDL_LOCATION;
    }

}
